# Generated by Django 4.0 on 2022-01-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='author_id',
            new_name='author',
        ),
    ]
