# Generated by Django 4.0 on 2022-01-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_rename_author_id_url_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Сокращенные ссылки'},
        ),
        migrations.AlterField(
            model_name='url',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Кто создал?'),
        ),
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorted_url',
            field=models.SlugField(max_length=8, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
